/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: address_book.proto */

#ifndef PROTOBUF_C_address_5fbook_2eproto__INCLUDED
#define PROTOBUF_C_address_5fbook_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Tutorial__Person Tutorial__Person;
typedef struct Tutorial__Person__PhoneNumber Tutorial__Person__PhoneNumber;
typedef struct Tutorial__Addressbook Tutorial__Addressbook;


/* --- enums --- */

typedef enum _Tutorial__Person__PhoneType {
  TUTORIAL__PERSON__PHONE_TYPE__MOBILE = 0,
  TUTORIAL__PERSON__PHONE_TYPE__HOME = 1,
  TUTORIAL__PERSON__PHONE_TYPE__WORK = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TUTORIAL__PERSON__PHONE_TYPE)
} Tutorial__Person__PhoneType;

/* --- messages --- */

struct  Tutorial__Person__PhoneNumber
{
  ProtobufCMessage base;
  char *number;
  protobuf_c_boolean has_type;
  Tutorial__Person__PhoneType type;
};
#define TUTORIAL__PERSON__PHONE_NUMBER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tutorial__person__phone_number__descriptor) \
    , NULL, 0, TUTORIAL__PERSON__PHONE_TYPE__HOME }


struct  Tutorial__Person
{
  ProtobufCMessage base;
  char *name;
  int32_t id;
  char *email;
  size_t n_phones;
  Tutorial__Person__PhoneNumber **phones;
};
#define TUTORIAL__PERSON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tutorial__person__descriptor) \
    , NULL, 0, NULL, 0,NULL }


struct  Tutorial__Addressbook
{
  ProtobufCMessage base;
  size_t n_people;
  Tutorial__Person **people;
};
#define TUTORIAL__ADDRESSBOOK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tutorial__addressbook__descriptor) \
    , 0,NULL }


/* Tutorial__Person__PhoneNumber methods */
void   tutorial__person__phone_number__init
                     (Tutorial__Person__PhoneNumber         *message);
/* Tutorial__Person methods */
void   tutorial__person__init
                     (Tutorial__Person         *message);
size_t tutorial__person__get_packed_size
                     (const Tutorial__Person   *message);
size_t tutorial__person__pack
                     (const Tutorial__Person   *message,
                      uint8_t             *out);
size_t tutorial__person__pack_to_buffer
                     (const Tutorial__Person   *message,
                      ProtobufCBuffer     *buffer);
Tutorial__Person *
       tutorial__person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tutorial__person__free_unpacked
                     (Tutorial__Person *message,
                      ProtobufCAllocator *allocator);
/* Tutorial__Addressbook methods */
void   tutorial__addressbook__init
                     (Tutorial__Addressbook         *message);
size_t tutorial__addressbook__get_packed_size
                     (const Tutorial__Addressbook   *message);
size_t tutorial__addressbook__pack
                     (const Tutorial__Addressbook   *message,
                      uint8_t             *out);
size_t tutorial__addressbook__pack_to_buffer
                     (const Tutorial__Addressbook   *message,
                      ProtobufCBuffer     *buffer);
Tutorial__Addressbook *
       tutorial__addressbook__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tutorial__addressbook__free_unpacked
                     (Tutorial__Addressbook *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Tutorial__Person__PhoneNumber_Closure)
                 (const Tutorial__Person__PhoneNumber *message,
                  void *closure_data);
typedef void (*Tutorial__Person_Closure)
                 (const Tutorial__Person *message,
                  void *closure_data);
typedef void (*Tutorial__Addressbook_Closure)
                 (const Tutorial__Addressbook *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor tutorial__person__descriptor;
extern const ProtobufCMessageDescriptor tutorial__person__phone_number__descriptor;
extern const ProtobufCEnumDescriptor    tutorial__person__phone_type__descriptor;
extern const ProtobufCMessageDescriptor tutorial__addressbook__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_address_5fbook_2eproto__INCLUDED */
